
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppFooter': typeof import("../components/AppFooter.vue")['default']
    'AppHeader': typeof import("../components/AppHeader.vue")['default']
    'AtomsContainer': typeof import("../components/atoms/Container.vue")['default']
    'AtomsLinkBtn': typeof import("../components/atoms/LinkBtn.vue")['default']
    'AtomsNavLink': typeof import("../components/atoms/NavLink.vue")['default']
    'AtomsSwiperNavButton': typeof import("../components/atoms/SwiperNavButton.vue")['default']
    'AtomsTitle': typeof import("../components/atoms/Title.vue")['default']
    'BlocksFooterNavBlock': typeof import("../components/blocks/FooterNavBlock.vue")['default']
    'CardsKeyBenefit': typeof import("../components/cards/KeyBenefit.vue")['default']
    'CardsPodCast': typeof import("../components/cards/PodCast.vue")['default']
    'CardsRecentPod': typeof import("../components/cards/RecentPod.vue")['default']
    'ElementsDropDown': typeof import("../components/elements/DropDown.vue")['default']
    'ElementsThemeSwitcher': typeof import("../components/elements/ThemeSwitcher.vue")['default']
    'ElementsIconsDark': typeof import("../components/elements/icons/Dark.vue")['default']
    'ElementsIconsLight': typeof import("../components/elements/icons/Light.vue")['default']
    'ElementsIconsSystem': typeof import("../components/elements/icons/System.vue")['default']
    'IconsAppLogo': typeof import("../components/icons/AppLogo.vue")['default']
    'IconsNextIco': typeof import("../components/icons/NextIco.vue")['default']
    'IconsPrevIco': typeof import("../components/icons/PrevIco.vue")['default']
    'SectionsAboutPodux': typeof import("../components/sections/AboutPodux.vue")['default']
    'SectionsCallToAction': typeof import("../components/sections/CallToAction.vue")['default']
    'SectionsWhyUs': typeof import("../components/sections/WhyUs.vue")['default']
    'SectionsHomeHeroSection': typeof import("../components/sections/home/HeroSection.vue")['default']
    'SectionsHomeLatestPodcast': typeof import("../components/sections/home/LatestPodcast.vue")['default']
    'SectionsHomePopularPodcasts': typeof import("../components/sections/home/PopularPodcasts.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppFooter': typeof import("../components/AppFooter.vue")['default']
    'LazyAppHeader': typeof import("../components/AppHeader.vue")['default']
    'LazyAtomsContainer': typeof import("../components/atoms/Container.vue")['default']
    'LazyAtomsLinkBtn': typeof import("../components/atoms/LinkBtn.vue")['default']
    'LazyAtomsNavLink': typeof import("../components/atoms/NavLink.vue")['default']
    'LazyAtomsSwiperNavButton': typeof import("../components/atoms/SwiperNavButton.vue")['default']
    'LazyAtomsTitle': typeof import("../components/atoms/Title.vue")['default']
    'LazyBlocksFooterNavBlock': typeof import("../components/blocks/FooterNavBlock.vue")['default']
    'LazyCardsKeyBenefit': typeof import("../components/cards/KeyBenefit.vue")['default']
    'LazyCardsPodCast': typeof import("../components/cards/PodCast.vue")['default']
    'LazyCardsRecentPod': typeof import("../components/cards/RecentPod.vue")['default']
    'LazyElementsDropDown': typeof import("../components/elements/DropDown.vue")['default']
    'LazyElementsThemeSwitcher': typeof import("../components/elements/ThemeSwitcher.vue")['default']
    'LazyElementsIconsDark': typeof import("../components/elements/icons/Dark.vue")['default']
    'LazyElementsIconsLight': typeof import("../components/elements/icons/Light.vue")['default']
    'LazyElementsIconsSystem': typeof import("../components/elements/icons/System.vue")['default']
    'LazyIconsAppLogo': typeof import("../components/icons/AppLogo.vue")['default']
    'LazyIconsNextIco': typeof import("../components/icons/NextIco.vue")['default']
    'LazyIconsPrevIco': typeof import("../components/icons/PrevIco.vue")['default']
    'LazySectionsAboutPodux': typeof import("../components/sections/AboutPodux.vue")['default']
    'LazySectionsCallToAction': typeof import("../components/sections/CallToAction.vue")['default']
    'LazySectionsWhyUs': typeof import("../components/sections/WhyUs.vue")['default']
    'LazySectionsHomeHeroSection': typeof import("../components/sections/home/HeroSection.vue")['default']
    'LazySectionsHomeLatestPodcast': typeof import("../components/sections/home/LatestPodcast.vue")['default']
    'LazySectionsHomePopularPodcasts': typeof import("../components/sections/home/PopularPodcasts.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppFooter: typeof import("../components/AppFooter.vue")['default']
export const AppHeader: typeof import("../components/AppHeader.vue")['default']
export const AtomsContainer: typeof import("../components/atoms/Container.vue")['default']
export const AtomsLinkBtn: typeof import("../components/atoms/LinkBtn.vue")['default']
export const AtomsNavLink: typeof import("../components/atoms/NavLink.vue")['default']
export const AtomsSwiperNavButton: typeof import("../components/atoms/SwiperNavButton.vue")['default']
export const AtomsTitle: typeof import("../components/atoms/Title.vue")['default']
export const BlocksFooterNavBlock: typeof import("../components/blocks/FooterNavBlock.vue")['default']
export const CardsKeyBenefit: typeof import("../components/cards/KeyBenefit.vue")['default']
export const CardsPodCast: typeof import("../components/cards/PodCast.vue")['default']
export const CardsRecentPod: typeof import("../components/cards/RecentPod.vue")['default']
export const ElementsDropDown: typeof import("../components/elements/DropDown.vue")['default']
export const ElementsThemeSwitcher: typeof import("../components/elements/ThemeSwitcher.vue")['default']
export const ElementsIconsDark: typeof import("../components/elements/icons/Dark.vue")['default']
export const ElementsIconsLight: typeof import("../components/elements/icons/Light.vue")['default']
export const ElementsIconsSystem: typeof import("../components/elements/icons/System.vue")['default']
export const IconsAppLogo: typeof import("../components/icons/AppLogo.vue")['default']
export const IconsNextIco: typeof import("../components/icons/NextIco.vue")['default']
export const IconsPrevIco: typeof import("../components/icons/PrevIco.vue")['default']
export const SectionsAboutPodux: typeof import("../components/sections/AboutPodux.vue")['default']
export const SectionsCallToAction: typeof import("../components/sections/CallToAction.vue")['default']
export const SectionsWhyUs: typeof import("../components/sections/WhyUs.vue")['default']
export const SectionsHomeHeroSection: typeof import("../components/sections/home/HeroSection.vue")['default']
export const SectionsHomeLatestPodcast: typeof import("../components/sections/home/LatestPodcast.vue")['default']
export const SectionsHomePopularPodcasts: typeof import("../components/sections/home/PopularPodcasts.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppFooter: typeof import("../components/AppFooter.vue")['default']
export const LazyAppHeader: typeof import("../components/AppHeader.vue")['default']
export const LazyAtomsContainer: typeof import("../components/atoms/Container.vue")['default']
export const LazyAtomsLinkBtn: typeof import("../components/atoms/LinkBtn.vue")['default']
export const LazyAtomsNavLink: typeof import("../components/atoms/NavLink.vue")['default']
export const LazyAtomsSwiperNavButton: typeof import("../components/atoms/SwiperNavButton.vue")['default']
export const LazyAtomsTitle: typeof import("../components/atoms/Title.vue")['default']
export const LazyBlocksFooterNavBlock: typeof import("../components/blocks/FooterNavBlock.vue")['default']
export const LazyCardsKeyBenefit: typeof import("../components/cards/KeyBenefit.vue")['default']
export const LazyCardsPodCast: typeof import("../components/cards/PodCast.vue")['default']
export const LazyCardsRecentPod: typeof import("../components/cards/RecentPod.vue")['default']
export const LazyElementsDropDown: typeof import("../components/elements/DropDown.vue")['default']
export const LazyElementsThemeSwitcher: typeof import("../components/elements/ThemeSwitcher.vue")['default']
export const LazyElementsIconsDark: typeof import("../components/elements/icons/Dark.vue")['default']
export const LazyElementsIconsLight: typeof import("../components/elements/icons/Light.vue")['default']
export const LazyElementsIconsSystem: typeof import("../components/elements/icons/System.vue")['default']
export const LazyIconsAppLogo: typeof import("../components/icons/AppLogo.vue")['default']
export const LazyIconsNextIco: typeof import("../components/icons/NextIco.vue")['default']
export const LazyIconsPrevIco: typeof import("../components/icons/PrevIco.vue")['default']
export const LazySectionsAboutPodux: typeof import("../components/sections/AboutPodux.vue")['default']
export const LazySectionsCallToAction: typeof import("../components/sections/CallToAction.vue")['default']
export const LazySectionsWhyUs: typeof import("../components/sections/WhyUs.vue")['default']
export const LazySectionsHomeHeroSection: typeof import("../components/sections/home/HeroSection.vue")['default']
export const LazySectionsHomeLatestPodcast: typeof import("../components/sections/home/LatestPodcast.vue")['default']
export const LazySectionsHomePopularPodcasts: typeof import("../components/sections/home/PopularPodcasts.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
